require:
  - 'rubocop-performance'
  - 'rubocop-rails'
  - 'rubocop-minitest'
  - 'rubocop-rake'

AllCops:
  NewCops: enable
  # Don't run rubocop on these files/directories
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'lib/templates/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'test/dummy/**/*'

Layout/LineLength:
  Max: 80
  Exclude:
    - 'unified_settings.gemspec'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'unified_settings.gemspec'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 100

Minitest/MultipleAssertions:
  Max: 10

Rails/RakeEnvironment:
  Exclude:
    - 'Rakefile'

Rails/RefuteMethods:
  Exclude:
    - 'test/**/*'
